# Default configuration for DiamonDespair
# Created by none other than GnomeffinWay of Entropolis
#
# Come check out our site at www.entropolis.co

# Replacement field must be a valid block ID
# Default replacement is a carrot

# Activator field (item to be replaced) must be a valid block ID
# Default activator is diamond ore
activator: 56

# Replacement field must be a valid block ID
# Default replacement is a carrot
replacement: 141

# Individual field determines whether this affects blocks server-wide
# or only specific players.
# Default setting is server-wide (false)
individual: false

# Determines whether the original blocks exp drops still happen
# True->Block is replaced, but can still drop exp
# Default value is false
exp-drop: false
